CONFIGURATION_FILE_PATH = '/configuration.json'
RENDER_CONFIGURATION_FILE_PATH = '/render_config.py'
DEFAULT_RENDER_CONFIGURATION_FILE_PATH = '/src/default_render_config.py'
HISTORY_FILE_PATH = '/public/updates.txt'
LOG_FILE_PATH = '/public/log.txt'
MINECRAFT_TEXTURES_PATH = '/build/textures.jar'
WORLD_BACKUP_PATH = '/build/world.tar.gz'
