name: Build and Publish image

on:
  push:
  schedule:
    - cron: '0 9 * * 1,3,5'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build-and-Publish

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/minemap:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
